<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 1,
                'gender' => 1,
                'year_of_birth' => 1995,
                'address' => 'Admin Thể hình 24h',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'name' => 'Huấn luyện viên 1',
                'email' => 'coach1@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 2,
                'gender' => 1,
                'year_of_birth' => 1995,
                'address' => 'Bắc Giang',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'name' => 'Huấn luyện viên 2',
                'email' => 'coach2@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 2,
                'gender' => 1,
                'year_of_birth' => 1995,
                'address' => 'Bắc Giang',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'name' => 'Huấn luyện viên 3',
                'email' => 'coach3@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 2,
                'gender' => 1,
                'year_of_birth' => 1995,
                'address' => 'Bắc Giang',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'name' => 'Huấn luyện viên 4',
                'email' => 'coach4@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 2,
                'gender' => 1,
                'year_of_birth' => 1995,
                'address' => 'Bắc Giang',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'name' => 'Huấn luyện viên 5',
                'email' => 'coach5@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 2,
                'gender' => 1,
                'year_of_birth' => 1995,
                'address' => 'Bắc Giang',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'name' => 'Huấn luyện viên 6',
                'email' => 'coach6@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 2,
                'gender' => 1,
                'year_of_birth' => 1995,
                'address' => 'Bắc Giang',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 1',
                'email' => 'member1@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 1,
                'year_of_birth' => 1995,
                'address' => 'Member số 1 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 2',
                'email' => 'member2@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 0,
                'year_of_birth' => 1994,
                'address' => 'Member số 2 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 3',
                'email' => 'member3@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 1,
                'year_of_birth' => 1993,
                'address' => 'Member số 3 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 4',
                'email' => 'member4@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 1,
                'year_of_birth' => 1995,
                'address' => 'Member số 4 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 5',
                'email' => 'member5@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 0,
                'year_of_birth' => 1994,
                'address' => 'Member số 5 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 6',
                'email' => 'member6@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 1,
                'year_of_birth' => 1992,
                'address' => 'Member số 6 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 7',
                'email' => 'member7@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 1,
                'year_of_birth' => 1992,
                'address' => 'Member số 7 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 8',
                'email' => 'member8@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 0,
                'year_of_birth' => 1992,
                'address' => 'Member số 8 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 9',
                'email' => 'member9@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 1,
                'year_of_birth' => 1992,
                'address' => 'Member số 9 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 10',
                'email' => 'member10@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 1,
                'year_of_birth' => 1992,
                'address' => 'Member số 10 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 11',
                'email' => 'member11@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 0,
                'year_of_birth' => 1992,
                'address' => 'Member số 11 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],[
                'name' => 'Thành viên 12',
                'email' => 'member12@gmail.com',
                'password' => bcrypt('123456'),
                'level' => 3,
                'gender' => 1,
                'year_of_birth' => 1992,
                'address' => 'Member số 12 Việt Nam',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]
        ]);
    }
}
